service: cloud-hack-websocket

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  
  # AWS Academy configuration
  profile: default
  
  # Use the existing LabRole ARN for AWS Academy
  iam:
    role: arn:aws:iam::520247722169:role/LabRole
      
  environment:
    TABLE_NAME: ${self:custom.reportsTableName}
    CONNECTIONS_TABLE: ${self:custom.connectionsTableName}
    USERS_TABLE: ${self:custom.usersTableName}

custom:
  reportsTableName: ReportsTable-${self:provider.stage}
  connectionsTableName: ConnectionsTable-${self:provider.stage}
  usersTableName: UsersTable-${self:provider.stage}

functions:
  # WebSocket Connect Lambda
  wsConnect:
    handler: src/connect.lambda_handler
    description: Handle WebSocket connections
    events:
      - websocket:
          route: $connect
    environment:
      CONNECTIONS_TABLE: ${self:custom.connectionsTableName}

  # WebSocket Disconnect Lambda
  wsDisconnect:
    handler: src/disconnect.lambda_handler
    description: Handle WebSocket disconnections
    events:
      - websocket:
          route: $disconnect
    environment:
      CONNECTIONS_TABLE: ${self:custom.connectionsTableName}

resources:
  Resources:
    # DynamoDB Table for Reports/Incidents
    ReportsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.reportsTableName}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        Tags:
          - Key: Name
            Value: ${self:custom.reportsTableName}
          - Key: Environment
            Value: ${self:provider.stage}

    # DynamoDB Table for WebSocket Connections
    ConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.connectionsTableName}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        Tags:
          - Key: Name
            Value: ${self:custom.connectionsTableName}
          - Key: Environment
            Value: ${self:provider.stage}

    # DynamoDB Table for Users (Authentication)
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.usersTableName}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        Tags:
          - Key: Name
            Value: ${self:custom.usersTableName}
          - Key: Environment
            Value: ${self:provider.stage}

  Outputs:
    # WebSocket API Endpoint
    WebSocketUrl:
      Description: WebSocket API endpoint URL
      Value:
        Fn::Sub: wss://${WebsocketsApi}.execute-api.${AWS::Region}.amazonaws.com/${self:provider.stage}
      Export:
        Name: ${self:service}-${self:provider.stage}-ws-api-url

    # WebSocket API ID (needed for Fargate to send messages)
    WebSocketApiId:
      Description: WebSocket API ID
      Value:
        Ref: WebsocketsApi
      Export:
        Name: ${self:service}-${self:provider.stage}-ws-api-id

    # DynamoDB Tables
    ReportsTableName:
      Description: DynamoDB table for incident reports
      Value: ${self:custom.reportsTableName}
      Export:
        Name: ${self:service}-${self:provider.stage}-reports-table

    ConnectionsTableName:
      Description: DynamoDB table for WebSocket connections
      Value: ${self:custom.connectionsTableName}
      Export:
        Name: ${self:service}-${self:provider.stage}-connections-table

    UsersTableName:
      Description: DynamoDB table for user authentication
      Value: ${self:custom.usersTableName}
      Export:
        Name: ${self:service}-${self:provider.stage}-users-table

package:
  patterns:
    - '!.git/**'
    - '!.gitignore'
    - '!.vscode/**'
    - '!node_modules/**'
    - '!__pycache__/**'
    - '!*.pyc'
    - '!venv/**'
    - '!.env'
    - '!frontend/**'
    - '!docs/**'
    - '!*.md'
    - 'src/connect.py'
    - 'src/disconnect.py'
