AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >-
  SAM template that creates a DynamoDB table (ReportsTable) and a Lambda
  function (ReportsFunction) fronted by API Gateway. Table is on-demand.

Globals:
  Function:
    Runtime: python3.9
    Timeout: 10
    MemorySize: 128

Resources:
  ReportsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ReportsTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  ConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ConnectionsTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: connectionId
          AttributeType: S
      KeySchema:
        - AttributeName: connectionId
          KeyType: HASH

  ReportsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ReportsFunction
      Handler: app.lambda_handler
      CodeUri: src/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ReportsTable
        - Statement:
            - Effect: Allow
              Action:
                - execute-api:ManageConnections
              Resource: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebsocketsApi}/*/*
      Events:
        IncidentesApi:
          Type: Api
          Properties:
            Path: /incidentes
            Method: GET
        IncidentesApiPost:
          Type: Api
          Properties:
            Path: /incidentes
            Method: POST
      Environment:
        Variables:
          TABLE_NAME: !Ref ReportsTable
          CONNECTIONS_TABLE: !Ref ConnectionsTable
          WS_API_ID: !Ref WebsocketsApi
          WS_STAGE: prod

  # WebSocket API (ApiGateway V2)
  WebsocketsApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: IncidentesWebsocketApi
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"

  WebsocketsStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref WebsocketsApi
      StageName: prod
      AutoDeploy: true

  # Connect Lambda
  ConnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ConnectFunction
      Handler: connect.lambda_handler
      CodeUri: src/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConnectionsTable

  # Disconnect Lambda
  DisconnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DisconnectFunction
      Handler: disconnect.lambda_handler
      CodeUri: src/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConnectionsTable

  # Integration and routes for $connect
  ConnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebsocketsApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ConnectFunction.Arn}/invocations

  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebsocketsApi
      RouteKey: "$connect"
      AuthorizationType: NONE
      Target: !Sub integrations/${ConnectIntegration}

  ConnectPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ConnectFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebsocketsApi}/*/$connect

  # Integration and routes for $disconnect
  DisconnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebsocketsApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DisconnectFunction.Arn}/invocations

  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebsocketsApi
      RouteKey: "$disconnect"
      AuthorizationType: NONE
      Target: !Sub integrations/${DisconnectIntegration}

  DisconnectPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref DisconnectFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebsocketsApi}/*/$disconnect

Outputs:
  ApiUrl:
    Description: "Invoke URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
    Export:
      Name: ReportsApiUrl
